pipeline {
    agent any
    stages {
        stage('Example') {
            steps {
               bat "C:/JDK/jdk-15.0.2/bin\java.exe -Dfile.encoding=UTF-8 -classpath D:\repositories\Java-Final\elevator\target\classes;C:\Users\Barys_Drahunou\.m2\repository\org\apache\logging\log4j\log4j-api\2.13.3\log4j-api-2.13.3.jar;C:\Users\Barys_Drahunou\.m2\repository\org\apache\logging\log4j\log4j-core\2.13.3\log4j-core-2.13.3.jar Main"
            }
        }
    }
}